# -*- coding: utf-8 -*-
"""Movie recommended system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tNI7Lxd_f3IPKgcflHZeqy1U0klVvz6q
"""

import numpy as np
import pandas as pd

movies=pd.read_csv("/content/tmdb_5000_movies.csv")
credits=pd.read_csv("/content/tmdb_5000_credits.csv")

movies.head(1)

"""Merge kar rahe hai title ke basis par"""

movies=movies.merge(credits,on='title')

movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.head()

"""ek naya dataframe bana naa h jisme movies_id,title ko chhor kar sab ko add kar denge

"""

movies.isnull().sum()

movies.dropna(inplace=True)

movies.iloc[1].genres

import ast
def convert(obj):
    L=[]
    for i in ast.literal_eval(obj) :
        L.append(i['name'])
    return L

movies['genres']=movies['genres'].apply(convert)

movies.head(5)

movies['keywords']=movies['keywords'].apply(convert)

movies.head(4)

"""case se top 3 actor nikalna h"""

def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj) :
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

movies['cast']=movies['cast'].apply(convert3)

movies.head(4)

def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj) :
        if i['job']=='Director':
            L.append(i['name'])
            break
    return L

movies['crew']=movies['crew'].apply(fetch_director)

movies.head(1)

movies['overview'][0]

movies['overview'].apply(lambda x:x.split())

movies.head(1)

movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

movies.head(1)

movies['tags'] = movies['overview'] + " " + \
                 movies['genres'].apply(lambda x: " ".join(x)) + " " + \
                 movies['keywords'].apply(lambda x: " ".join(x)) + " " + \
                 movies['cast'].apply(lambda x: " ".join(x)) + " " + \
                 movies['crew'].apply(lambda x: " ".join(x))

movies.head(2)

new_df=movies[['movie_id','title','tags']]

new_df

new_df['tags'][0]

new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

new_df['tags']=new_df['tags'].apply(stem)

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer(max_features=5000,stop_words='english')

vectors=cv.fit_transform(new_df['tags']).toarray()

cv.get_feature_names_out()

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors)
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distances=similarity[movie_index]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

recommend("Spider-Man 2")

import pickle
pickle.dump(new_df,open('movies.pkl','wb'))

new_df['title'].values

pickle.dump(similarity,open('similarity.pkl','wb'))

pickle.dump(new_df.to_dict(),open('movie_dict_pickle','wb'))

pickle.dump(similarity,open('similarity.pkl','wb'))